# Generated by Django 4.1.5 on 2023-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='foro',
        ),
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%y/%m/'),
        ),
    ]
